//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockUniverse
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public Contact()
        {
            this.ContactsDetails = new HashSet<ContactsDetail>();
        }

        public int Contact_ID { get; set; }
        [Required(ErrorMessage = "Không được để trống tên khách hàng")]
        public string Customer_Name { get; set; }
        [StringLength(15, ErrorMessage = "Số điện thoại phải từ 10-12 số")]
        [Required(ErrorMessage = "Không được để trống SDT")]
        [Range(0, Int64.MaxValue, ErrorMessage = "Số điện thoại phải từ 10-12 số")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Không được để trống Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Không được để trống Địa chỉ")]
        public string Address { get; set; }
        public int Status { get; set; }
        public virtual ICollection<ContactsDetail> ContactsDetails { get; set; }
    }
}
