//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockUniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int Order_ID { get; set; }
        public System.DateTime Order_Date { get; set; }
        public System.DateTime Delivery_Date { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Email { get; set; }
        public string Deliver_Address { get; set; }
        public int Deliver_Status { get; set; }
        public Nullable<System.DateTime> Order_ChangeDate { get; set; }
        public decimal Total_Price { get; set; }
    
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
    }
}
