//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockUniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        public ProductTable()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int Watch_ID { get; set; }
        public string Watch_Name { get; set; }
<<<<<<< HEAD
        public string Watch_Description { get; set; }
        public int WatchType_ID { get; set; }
=======

        [Required(ErrorMessage ="Bạn chưa nhập mô tả đồng hồ ")]
        public string Watch_Description { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập thông số đồng hồ ")]
        public string Watch_Static { get; set; }    
        
        [Required(ErrorMessage ="Bạn chưa nhập giá niêm yết ")]
>>>>>>> 54c0f5e36ceb4ee5b152586988c9ed773a1fcfea
        public decimal Original_Price { get; set; }
        public decimal Selling_Price { get; set; }
        public int InStock { get; set; }
<<<<<<< HEAD
        public string Watch_Static { get; set; }
=======

        public int WatchType_ID { get; set; }

       

>>>>>>> 54c0f5e36ceb4ee5b152586988c9ed773a1fcfea
        public string Image { get; set; }
    
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
