//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockUniverse
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;  
    
    public partial class ProductTable
    {
        public ProductTable()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
        
       
        public int Watch_ID { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập tên đồng hồ ")]
        public string Watch_Name { get; set; }

        [Required(ErrorMessage ="Bạn chưa nhập mô tả đồng hồ ")]
        public string Watch_Description { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập thông số đồng hồ ")]
        public string Watch_Static { get; set; }    
        
        [Required(ErrorMessage ="Bạn chưa nhập giá niêm yết ")]
        public decimal Original_Price { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập giá khuyến mãi ")]
        public decimal Selling_Price { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập số lượng đồng hồ ")]
        public int InStock { get; set; }

        public int WatchType_ID { get; set; }

       

        public string Image { get; set; }
    
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
