//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockUniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLTT
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> SDT { get; set; }
        public string DiaChi { get; set; }
    }
}
