//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockUniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyDH
    {
        public int ID { get; set; }
        public string TenDH { get; set; }
        public string LoaiDH { get; set; }
        public string ThongTinDH { get; set; }
        public byte[] HinhAnhDH { get; set; }
        public decimal GiaTien { get; set; }
        public string SoLuong { get; set; }
    }
}
